"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-16

Creates the full initial schema for the marketplace on PostgreSQL.

The schema is built directly from ``app.models.models`` metadata instead of
hand-written DDL. The original migration targeted MySQL (``mysql_engine`` table
options, native ``ENUM`` types). Driving DDL from the SQLAlchemy metadata keeps
this migration the exact mirror of the models, is portable to PostgreSQL, and
lets ``create_all`` de-duplicate shared objects correctly. Enums are emitted as
VARCHAR + CHECK constraints (see ``models.Enum``), so no native enum types are
created. Subsequent schema changes use ordinary autogenerated migrations.
"""
from alembic import op

# Import the models so the full metadata is populated before create_all.
from app.core.database import Base
import app.models.models  # noqa: F401 – registers all ORM models

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
